name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.HOST }}

          username: ${{ secrets.USERNAME }}

          password: ${{ secrets.PASSWORD }}

          script: |
            cd /srv/dashboard.api.sfere.pro
            git pull
            npm i
            npm run build
